.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-fido-credentials-update-user 1  ckman 
.SH NAME
ckman\-fido\-credentials\-update\-user \- Rename a resident credential\*(Aqs user (fields not given keep their current values; pass an empty string to clear a field)
.SH SYNOPSIS
\fBckman\-fido\-credentials\-update\-user\fR [\fB\-u\fR|\fB\-\-username\fR] [\fB\-n\fR|\fB\-\-display\-name\fR] [\fB\-P\fR|\fB\-\-pin\fR] [\fB\-f\fR|\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICREDENTIAL_ID\fR> 
.SH DESCRIPTION
Rename a resident credential\*(Aqs user (fields not given keep their current values; pass an empty string to clear a field)
.SH OPTIONS
.TP
\fB\-u\fR, \fB\-\-username\fR \fI<USERNAME>\fR
New username
.TP
\fB\-n\fR, \fB\-\-display\-name\fR \fI<DISPLAY_NAME>\fR
New display name
.TP
\fB\-P\fR, \fB\-\-pin\fR \fI<PIN>\fR
FIDO2 PIN (prompted when omitted)
.TP
\fB\-f\fR, \fB\-\-force\fR
Do not ask for confirmation
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICREDENTIAL_ID\fR>
A unique substring of the credential ID (as shown by "list")
