.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-list 1  ckman 
.SH NAME
ckman\-list \- List connected CanoKeys
.SH SYNOPSIS
\fBckman\-list\fR [\fB\-\-serials\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List connected CanoKeys
.SH OPTIONS
.TP
\fB\-\-serials\fR
Only output serial numbers, one per line
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
