.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-admin-pin-change 1  ckman 
.SH NAME
ckman\-config\-admin\-pin\-change \- Change the device Admin PIN (prompts for the current and new PIN)
.SH SYNOPSIS
\fBckman\-config\-admin\-pin\-change\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Change the device Admin PIN (prompts for the current and new PIN)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
