.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-oath-serial 1  ckman 
.SH NAME
ckman\-oath\-serial \- Print the device serial as answered by the OATH applet
.SH SYNOPSIS
\fBckman\-oath\-serial\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print the device serial as answered by the OATH applet
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
