.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-openpgp-access-change-admin-pin 1  ckman 
.SH NAME
ckman\-openpgp\-access\-change\-admin\-pin \- Change the Admin PIN
.SH SYNOPSIS
\fBckman\-openpgp\-access\-change\-admin\-pin\fR [\fB\-a\fR|\fB\-\-admin\-pin\fR] [\fB\-n\fR|\fB\-\-new\-admin\-pin\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Change the Admin PIN
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-admin\-pin\fR \fI<ADMIN_PIN>\fR
Current Admin PIN (prompted when omitted)
.TP
\fB\-n\fR, \fB\-\-new\-admin\-pin\fR \fI<NEW_ADMIN_PIN>\fR
New Admin PIN (prompted when omitted)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
