.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-openpgp-keys-import 1  ckman 
.SH NAME
ckman\-openpgp\-keys\-import \- Import a private key (PEM/DER/PKCS#12: PKCS#8, PKCS#1, SEC1; a bundle contributes its first private key)
.SH SYNOPSIS
\fBckman\-openpgp\-keys\-import\fR [\fB\-\-algorithm\fR] [\fB\-p\fR|\fB\-\-password\fR] [\fB\-a\fR|\fB\-\-admin\-pin\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIKEY\fR> <\fIPRIVATE_KEY\fR> 
.SH DESCRIPTION
Import a private key (PEM/DER/PKCS#12: PKCS#8, PKCS#1, SEC1; a bundle contributes its first private key)
.SH OPTIONS
.TP
\fB\-\-algorithm\fR \fI<ALGORITHM>\fR
Set the slot\*(Aqs algorithm attributes first (discards any existing key)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
rsa2048
.IP \(bu 2
rsa3072
.IP \(bu 2
rsa4096
.IP \(bu 2
ecc\-p256
.IP \(bu 2
ecc\-p384
.IP \(bu 2
ecc\-p521
.IP \(bu 2
secp256k1
.IP \(bu 2
ed25519
.IP \(bu 2
x25519
.RE
.TP
\fB\-p\fR, \fB\-\-password\fR \fI<PASSWORD>\fR
Password used to decrypt the private key
.TP
\fB\-a\fR, \fB\-\-admin\-pin\fR \fI<ADMIN_PIN>\fR
Admin PIN (prompted when omitted)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIKEY\fR>
Key slot
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
sig
.IP \(bu 2
dec
.IP \(bu 2
aut
.RE
.TP
<\fIPRIVATE_KEY\fR>
File containing the private key (\*(Aq\-\*(Aq for stdin)
