.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-fido-credentials 1  ckman 
.SH NAME
ckman\-fido\-credentials \- Manage discoverable (resident) credentials
.SH SYNOPSIS
\fBckman\-fido\-credentials\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage discoverable (resident) credentials
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
ckman\-fido\-credentials\-list(1)
List resident credentials
.TP
ckman\-fido\-credentials\-delete(1)
Delete a resident credential
.TP
ckman\-fido\-credentials\-update\-user(1)
Rename a resident credential\*(Aqs user (fields not given keep their current values; pass an empty string to clear a field)
.TP
ckman\-fido\-credentials\-help(1)
Print this message or the help of the given subcommand(s)
