.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-piv-access-change-puk 1  ckman 
.SH NAME
ckman\-piv\-access\-change\-puk \- Change the PUK
.SH SYNOPSIS
\fBckman\-piv\-access\-change\-puk\fR [\fB\-p\fR|\fB\-\-puk\fR] [\fB\-n\fR|\fB\-\-new\-puk\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Change the PUK
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-puk\fR \fI<PUK>\fR
Current PUK (prompted when omitted)
.TP
\fB\-n\fR, \fB\-\-new\-puk\fR \fI<NEW_PUK>\fR
New PUK (prompted when omitted)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
