.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-keyboard-clear-keymap 1  ckman 
.SH NAME
ckman\-config\-keyboard\-clear\-keymap \- Clear the stored keyboard HID map
.SH SYNOPSIS
\fBckman\-config\-keyboard\-clear\-keymap\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Clear the stored keyboard HID map
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
