.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-piv-access-change-pin 1  ckman 
.SH NAME
ckman\-piv\-access\-change\-pin \- Change the PIV PIN
.SH SYNOPSIS
\fBckman\-piv\-access\-change\-pin\fR [\fB\-P\fR|\fB\-\-pin\fR] [\fB\-n\fR|\fB\-\-new\-pin\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Change the PIV PIN
.SH OPTIONS
.TP
\fB\-P\fR, \fB\-\-pin\fR \fI<PIN>\fR
Current PIN (prompted when omitted)
.TP
\fB\-n\fR, \fB\-\-new\-pin\fR \fI<NEW_PIN>\fR
New PIN (prompted when omitted)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
