.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-sm2 1  ckman 
.SH NAME
ckman\-config\-sm2 \- Show the CTAP SM2 configuration (3.0+; read\-only)
.SH SYNOPSIS
\fBckman\-config\-sm2\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the CTAP SM2 configuration (3.0+; read\-only)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
