.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-fido-touch-test 1  ckman 
.SH NAME
ckman\-fido\-touch\-test \- Ask the key to identify itself: touch it (or watch it blink) and report success or timeout
.SH SYNOPSIS
\fBckman\-fido\-touch\-test\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Ask the key to identify itself: touch it (or watch it blink) and report success or timeout
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
