.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-info 1  ckman 
.SH NAME
ckman\-config\-info \- Show the current device configuration
.SH SYNOPSIS
\fBckman\-config\-info\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the current device configuration
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
