.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-admin-pin-status 1  ckman 
.SH NAME
ckman\-config\-admin\-pin\-status \- Show the Admin PIN verification state and remaining retries
.SH SYNOPSIS
\fBckman\-config\-admin\-pin\-status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the Admin PIN verification state and remaining retries
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
