.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-piv-info 1  ckman 
.SH NAME
ckman\-piv\-info \- Display general status of the PIV application
.SH SYNOPSIS
\fBckman\-piv\-info\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display general status of the PIV application
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
