.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-reset 1  ckman 
.SH NAME
ckman\-config\-reset \- Reset the device to factory defaults, erasing all applets and PINs
.SH SYNOPSIS
\fBckman\-config\-reset\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Reset the device to factory defaults, erasing all applets and PINs
.SH OPTIONS
.TP
\fB\-\-force\fR
Do not ask for confirmation
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
