.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-fido-credentials-delete 1  ckman 
.SH NAME
ckman\-fido\-credentials\-delete \- Delete a resident credential
.SH SYNOPSIS
\fBckman\-fido\-credentials\-delete\fR [\fB\-P\fR|\fB\-\-pin\fR] [\fB\-f\fR|\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICREDENTIAL_ID\fR> 
.SH DESCRIPTION
Delete a resident credential
.SH OPTIONS
.TP
\fB\-P\fR, \fB\-\-pin\fR \fI<PIN>\fR
FIDO2 PIN (prompted when omitted)
.TP
\fB\-f\fR, \fB\-\-force\fR
Confirm deletion without prompting
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICREDENTIAL_ID\fR>
A unique substring of the credential ID (as shown by "list")
