.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-pass-info 1  ckman 
.SH NAME
ckman\-config\-pass\-info \- Show both PASS slot configurations
.SH SYNOPSIS
\fBckman\-config\-pass\-info\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show both PASS slot configurations
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
