.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-fido-config-toggle-always-uv 1  ckman 
.SH NAME
ckman\-fido\-config\-toggle\-always\-uv \- Toggle the "always require user verification" setting
.SH SYNOPSIS
\fBckman\-fido\-config\-toggle\-always\-uv\fR [\fB\-P\fR|\fB\-\-pin\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Toggle the "always require user verification" setting
.SH OPTIONS
.TP
\fB\-P\fR, \fB\-\-pin\fR \fI<PIN>\fR
Current PIN (prompted when omitted)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
