.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-oath-accounts-list 1  ckman 
.SH NAME
ckman\-oath\-accounts\-list \- List all accounts
.SH SYNOPSIS
\fBckman\-oath\-accounts\-list\fR [\fB\-H\fR|\fB\-\-show\-hidden\fR] [\fB\-o\fR|\fB\-\-oath\-type\fR] [\fB\-P\fR|\fB\-\-period\fR] [\fB\-p\fR|\fB\-\-password\fR] [\fB\-\-remember\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List all accounts
.SH OPTIONS
.TP
\fB\-H\fR, \fB\-\-show\-hidden\fR
Include hidden accounts
.TP
\fB\-o\fR, \fB\-\-oath\-type\fR
Display the OATH type
.TP
\fB\-P\fR, \fB\-\-period\fR
Display the period
.TP
\fB\-p\fR, \fB\-\-password\fR \fI<PASSWORD>\fR
The password to unlock the OATH application
.TP
\fB\-\-remember\fR
Remember the password on this machine (long\-only: the global \-r/\-\-reader owns the short flag)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
