.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-config-nfc 1  ckman 
.SH NAME
ckman\-config\-nfc \- Turn NFC on or off
.SH SYNOPSIS
\fBckman\-config\-nfc\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISTATE\fR> 
.SH DESCRIPTION
Turn NFC on or off
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISTATE\fR>
Desired NFC state
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
on
.IP \(bu 2
off
.RE
