.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-oath-access-forget 1  ckman 
.SH NAME
ckman\-oath\-access\-forget \- Remove this device\*(Aqs stored password from the OS keyring
.SH SYNOPSIS
\fBckman\-oath\-access\-forget\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove this device\*(Aqs stored password from the OS keyring
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
