.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-oath-access-remember 1  ckman 
.SH NAME
ckman\-oath\-access\-remember \- Store the OATH password in the OS keyring to avoid entering it on each use
.SH SYNOPSIS
\fBckman\-oath\-access\-remember\fR [\fB\-p\fR|\fB\-\-password\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Store the OATH password in the OS keyring to avoid entering it on each use
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-password\fR \fI<PASSWORD>\fR
The current password
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
