.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-fido-reset 1  ckman 
.SH NAME
ckman\-fido\-reset \- Reset the FIDO application, deleting all credentials and the PIN
.SH SYNOPSIS
\fBckman\-fido\-reset\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Reset the FIDO application, deleting all credentials and the PIN.
.PP
The reset must be triggered immediately after the CanoKey is (re\-)inserted, and requires a touch to confirm.
.SH OPTIONS
.TP
\fB\-\-force\fR
Do not ask for confirmation; assume a freshly inserted key
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
