.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-oath-info 1  ckman 
.SH NAME
ckman\-oath\-info \- Display general status of the OATH application
.SH SYNOPSIS
\fBckman\-oath\-info\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display general status of the OATH application
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
