.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ckman-fido-blobs-read 1  ckman 
.SH NAME
ckman\-fido\-blobs\-read \- Read the whole largeBlobs array to a file (\*(Aq\-\*(Aq for stdout)
.SH SYNOPSIS
\fBckman\-fido\-blobs\-read\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIOUTPUT\fR> 
.SH DESCRIPTION
Read the whole largeBlobs array to a file (\*(Aq\-\*(Aq for stdout)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIOUTPUT\fR>
File to write the array to (\*(Aq\-\*(Aq for stdout)
